spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskTheRaven
    username: postgres
    password: 12345Do
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true



